services:
  tracker_nginx:
    image: nginx:1.21-alpine
    restart: on-failure
    depends_on:
      - tracker_telegram-api-server
    ports:
      - "80:80"
    volumes:
      - telegram-bot-api-data:/var/lib/telegram-bot-api
      - ./nginx:/etc/nginx/conf.d/
    networks:
      - bot-network

  tracker_telegram-api-server:
    image: aiogram/telegram-bot-api:latest
    restart: on-failure
    env_file:
      - .env
    volumes:
      - telegram-bot-api-data:/var/lib/telegram-bot-api
    ports:
      - "8081:8081"
    networks:
      - bot-network

  tracker_db:
    image: postgres:latest
    restart: always
    container_name: tracker_postgres-container
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - bot-network

  tracker_redis:
    image: redis:latest
    restart: always
    container_name: tracker_redis-container
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
    env_file:
      - '.env'
    ports:
      - "6379:6379"
    networks:
      - bot-network

  tracker_tg_bot:
    image: "bot"
    restart: always
    stop_signal: SIGINT
    container_name: tracker_bot-container
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    env_file:
      - '.env'
    depends_on:
      - tracker_db
      - tracker_redis
      - tracker_telegram-api-server
    networks:
      - bot-network

networks:
  bot-network:

volumes:
  telegram-bot-api-data:
    driver: "local"

  postgres_data:
