global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'tracker_service'
    static_configs:
      - targets: ['tracker_service:9090']

  - job_name: 'tracker_redis'
    static_configs:
      - targets: ['tracker_redis:6379']

  - job_name: 'tracker_db'
    static_configs:
      - targets: ['tracker_db:5432']
